/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityPopup: typeof import('./src/components/Defi/ActivityPopup.vue')['default']
    ButtonBar: typeof import('./src/components/common/ButtonBar/index.vue')['default']
    Copy: typeof import('./src/components/common/Copy/index.vue')['default']
    CurrencyItem: typeof import('./src/components/CurrencyList/currencyItem.vue')['default']
    CurrencyItemTrade: typeof import('./src/components/CurrencyList/currencyItem-trade.vue')['default']
    CurrencyList: typeof import('./src/components/CurrencyList/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    DropdownMenu: typeof import('./src/components/DropdownMenu/index.vue')['default']
    EditLeft: typeof import('./src/components/CurrencyList/editLeft.vue')['default']
    Empty: typeof import('./src/components/Empty/index.vue')['default']
    Error: typeof import('./src/components/common/Loadable/component/Error.vue')['default']
    FreezePopup: typeof import('./src/components/Freeze/FreezePopup.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar/index.vue')['default']
    ImageLoad: typeof import('./src/components/common/ImageLoad/index.vue')['default']
    Left: typeof import('./src/components/CurrencyList/left.vue')['default']
    Loading: typeof import('./src/components/common/Loading/index.vue')['default']
    Logo: typeof import('./src/components/common/Logo/index.vue')['default']
    LogoHeader: typeof import('./src/components/LogoHeader/index.vue')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
    Nodata: typeof import('./src/components/Nodata/index.vue')['default']
    OverlayPulic: typeof import('./src/components/Popup/overlayPulic.vue')['default']
    Popup: typeof import('./src/components/Popup/index.vue')['default']
    Public: typeof import('./src/components/Popup/public.vue')['default']
    QRCode: typeof import('./src/components/common/QRCode/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicePopup: typeof import('./src/components/CustomerService/ServicePopup.vue')['default']
    SvgLoad: typeof import('./src/components/common/SvgLoad/index.vue')['default']
    Tab: typeof import('./src/components/Tab/index.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar/index.vue')['default']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanDialog: typeof import('vant/es')['Dialog']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
